import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lahmidi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth focus:scroll-auto" lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
